# Generated by Django 5.0.14 on 2026-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
